### PR TITLE
Add new team members

### PR DESCRIPTION
**Pull request by TomWFox**
giphy-3
- @mtrezza https://community.parseplatform.org/t/vote-to-add-manuel-mtrezza-as-a-committer/473
- @TheFanatr https://community.parseplatform.org/t/vote-to-add-alex-fanat-thefanatr-as-a-committer/479
- @Sebc99 https://community.parseplatform.org/t/vote-to-add-sebc-sebc99-as-a-committer/477

### CODE REVIEW

**Comment by TomWFox** [comment]
Btw @mtrezza & @sebc99 we have a team channel on the slack group but I couldn't find either of you on there. It's not really been used yet but I though it might be useful for quick questions. You can join the slack with [this link](https://join.slack.com/t/parseopensource/shared_invite/zt-8w385vtf-gIxfSqORSyoK6RO~y3bHZA) let me know if you want to be added to the channel.

cc @tobiaspott @funkenstrahlen @drdaz @douglasmuraoka - also can't find any of you 🙂

**Comment by mtrezza** [comment]
@TomWFox Joined!

**Comment by TobiasPott** [comment]
@TomWFox Thank you for pointing us to the slack channel. I'm not that much into Slack but I'll check out the most convenient way for me to join in =).

**Comment by drdaz** [comment]
@TomWFox I had no idea there was a channel. I'll get in there.

**Comment by TobiasPott** [comment]
@TomWFox Finally took my time and grabbed the slack client and joined the channel and gave a short introduction there. =)

**Comment by TomWFox** [comment]
@Jawnnypoo sorry I missed you out, I can't find you in the slack group either.

**Pull request merged**
